#eureka:
#  client:
#    service-url:
#      defaultZone:
#        http://localhost:8761/eureka/
#
#server:
#  port: 8762
#spring:
#  application:
#    name: eureka-client
---
server:
  port: 8763
spring:
  application:
    name: eureka-client
  profiles: client1
eureka:
  client:
    service-url:
      defaultZone:
        http://peer1:8761/eureka/
---
server:
  port: 8764
spring:
  application:
    name: eureka-client
  profiles: client2
eureka:
  client:
    service-url:
      defaultZone:
        http://peer1:8761/eureka/


